### ISSUE TITLE
Trip Pin service code does not match deployment at http://services.odata.org/V4/TripPinServiceRW

### ISSUE THREAD

**Issue by MrTomWhite** [OData/ODataSamples#12]
It looks like there has been some divergence between the sample code in https://github.com/OData/ODataSamples/tree/master/Scenarios/TripPin and the deployment of the sample service at http://services.odata.org/V4/TripPinServiceRW. 

This is made more clear by comparing the metadata document obtained from a local deployment of master and the metadata document on the deployed example. The deployed document contains annotations which are not defined in the current sample code. 

Keeping these in sync will help make this a better resource for people learning to use and implement OData services. The simplest fix is to push changes to this repository.

**Comment by liqian19891011** [comment]
@MrTomWhite  Yes, it's true that the source code does not match. Sorry about the confusion and the reason is 
- http://services.odata.org/V4/TripPinServiceRW is actually implemented using **ODataLib** which is the core library of OData in .NET and Web API OData also build on this. 
- The source code on GitHub is a **Web API OData** implementation of TripPin and actually we have a service endpoint http://services.odata.org/TripPinWebApiService/. 
- So the problem actually is that ODataLib has a wider feature set than Web API OData so we publish the ODataLib implemented services to show as many OData features as possible. We have plans to open-source the code for ODataLib implementation but it will take some time for code clean up. And we are still struggling about whether public the two service endpoints or just one. Also like to hear your feedback.

**Comment by vojtechvit** [comment]
@liqian19891011 I think that you added the real TripPin implementation to the service on January 27 2015, so this ticket can be closed.
But if you want feedback - I really appreciated that you published both, because it explained the lack of features in the Web API version + I learned from it how to use ODataLib in some scenarios not supported by ConventionalModelBuilder.
Over time, however, I think that you should switch the TripPin service completely to Web API/RESTier to prove that they're production ready. Personally I had hard time persuading my company that Web API OData can be used at least partially - because we found many features missing and some bugs that I reported or +1ed. The use of custom tooling in the TripPin service just proves that those concerns are valid.
For trivial services the current state of Web API OData may be enough, but I don't think that OData standard targets small projects. It's complex and powerful, so I see it more suitable for enterprise and governments, where, however, the requirements on maturity of the tooling are higher.

**Comment by liqian19891011** [comment]
@vojtechvit   Appreciate your feedback ! 

1. About switching TripPin service to WebAPI/RESTier is a great idea. The original reason building TripPin is to show as much OData V4 sample as possible and with this reason we use ODataLib since it has the most support for V4 features. But over time, we do hear some feedback like you. I will created an issue.

2. I'm very interested in your companies scenarios where Web API OData can help. If it's not breaking any legal things, please share your scenarios and let's what we can help.

3. Yes, OData wants to be the industry standard for REST services. As you can see from our stacks in GitHub like http://github.com/OData/WebApi , OData (at least "Microsoft" .NET ) libraries are going open-sourced. So, we highly welcome community to contribute to the stacks directly. But still, we'd like to hear what you think Web API missing for corporate and governments needs, maybe some of your need are in our plan  :)

For my comments 2 and 3, you can either comments here or you can send email to odatafeedback@microsoft.com, the email account is for feedback of the .NET stacks of OData monitored by Microsoft OData team.  Thanks for your feedback again!

**Comment by liqian19891011** [comment]
Source of http://services.odata.org/V4/TripPinServiceRW has already been published at https://github.com/OData/ODataSamples/tree/master/Scenarios/TripPin/src/odatalib
